import { Global, Inject, Injectable, Module } from '@nestjs/common';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { APP_CONFIG, type AppConfig } from '../../config/config.module.js';

/**
 * Port for binary object storage (images). Keys are generated by the server only,
 * e.g. `businesses/<businessId>/<imageId>/thumb.webp`. S3 will be another implementation.
 */
export abstract class StorageProvider {
  abstract put(key: string, body: Buffer, contentType: string): Promise<void>;
  /** Returns null if the object does not exist. */
  abstract get(key: string): Promise<Buffer | null>;
  abstract deletePrefix(prefix: string): Promise<void>;
}

const SAFE_KEY = /^[a-z0-9][a-z0-9/_.-]*$/;

export function assertSafeKey(key: string): void {
  if (!SAFE_KEY.test(key) || key.includes('..') || key.includes('//')) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}

/** Development/test storage in a local folder. Refused in staging/production by config validation. */
@Injectable()
export class LocalDiskStorageProvider extends StorageProvider {
  private readonly root: string;

  constructor(@Inject(APP_CONFIG) config: AppConfig) {
    super();
    this.root = resolve(config.STORAGE_LOCAL_DIR);
  }

  /** The content type is not needed on disk (files are served with the type recorded by the caller). */
  async put(key: string, body: Buffer, _contentType: string): Promise<void> {
    const path = this.pathOf(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.pathOf(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }

  async deletePrefix(prefix: string): Promise<void> {
    await rm(this.pathOf(prefix), { recursive: true, force: true });
  }

  private pathOf(key: string): string {
    assertSafeKey(key);
    const path = resolve(join(this.root, key));
    if (!path.startsWith(this.root + sep)) throw new Error(`Storage key escapes root: ${key}`);
    return path;
  }
}

@Global()
@Module({
  providers: [{ provide: StorageProvider, useClass: LocalDiskStorageProvider }],
  exports: [StorageProvider],
})
export class StorageModule {}
